server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul
zuul:
  routes:
    producer-api:
      path: /producer-api/**
      url: producer
    consumer-api:
      path: /consumer-api/**
      serviceId: consumer



